### ISSUE TITLE
Installation instructions? 

### ISSUE THREAD

**Issue by ahof1704** [vivek-brown/NPJCOMPUMATS-03747#2]
Hi,

could you share the installation instructions of the version of the packages to run your code? 

Thanks

**Comment by vivekoommen** [comment]
Hi,

- I have updated the code for tensorflow==2.16.1
- See the requirements.txt file that has been added recently.
- Run: pip install -r requirements.txt for installing the required packages.
- For reference, the full list of packages with their versions are provided in full_package_list.txt

Hope this helps!

Regards,
Vivek
